# coding: utf-8

# flake8: noqa

"""
    ETAPI

    External Trilium API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@eliandoran.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AppInfo",
    "Attachment",
    "Attribute",
    "Branch",
    "CreateAttachment",
    "CreateNoteDef",
    "Error",
    "Login201Response",
    "LoginRequest",
    "Note",
    "NoteWithBranch",
    "RecentChange",
    "Revision",
    "SearchResponse",
    "UndeleteNote200Response",
]

# import apis into sdk package
from trilium_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from trilium_client.api_response import ApiResponse as ApiResponse
from trilium_client.api_client import ApiClient as ApiClient
from trilium_client.configuration import Configuration as Configuration
from trilium_client.exceptions import OpenApiException as OpenApiException
from trilium_client.exceptions import ApiTypeError as ApiTypeError
from trilium_client.exceptions import ApiValueError as ApiValueError
from trilium_client.exceptions import ApiKeyError as ApiKeyError
from trilium_client.exceptions import ApiAttributeError as ApiAttributeError
from trilium_client.exceptions import ApiException as ApiException

# import models into sdk package
from trilium_client.models.app_info import AppInfo as AppInfo
from trilium_client.models.attachment import Attachment as Attachment
from trilium_client.models.attribute import Attribute as Attribute
from trilium_client.models.branch import Branch as Branch
from trilium_client.models.create_attachment import CreateAttachment as CreateAttachment
from trilium_client.models.create_note_def import CreateNoteDef as CreateNoteDef
from trilium_client.models.error import Error as Error
from trilium_client.models.login201_response import Login201Response as Login201Response
from trilium_client.models.login_request import LoginRequest as LoginRequest
from trilium_client.models.note import Note as Note
from trilium_client.models.note_with_branch import NoteWithBranch as NoteWithBranch
from trilium_client.models.recent_change import RecentChange as RecentChange
from trilium_client.models.revision import Revision as Revision
from trilium_client.models.search_response import SearchResponse as SearchResponse
from trilium_client.models.undelete_note200_response import (
    UndeleteNote200Response as UndeleteNote200Response,
)
