# coding: utf-8

# flake8: noqa
"""
    ETAPI

    External Trilium API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@eliandoran.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from trilium_client.models.app_info import AppInfo
from trilium_client.models.attachment import Attachment
from trilium_client.models.attribute import Attribute
from trilium_client.models.branch import Branch
from trilium_client.models.create_attachment import CreateAttachment
from trilium_client.models.create_note_def import CreateNoteDef
from trilium_client.models.error import Error
from trilium_client.models.login201_response import Login201Response
from trilium_client.models.login_request import LoginRequest
from trilium_client.models.note import Note
from trilium_client.models.note_with_branch import NoteWithBranch
from trilium_client.models.recent_change import RecentChange
from trilium_client.models.revision import Revision
from trilium_client.models.search_response import SearchResponse
from trilium_client.models.undelete_note200_response import UndeleteNote200Response
