# coding: utf-8

"""
    ETAPI

    External Trilium API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@eliandoran.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class RecentChange(BaseModel):
    """
    Represents a recent change event (creation, modification, or deletion).
    """  # noqa: E501

    note_id: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None, alias="noteId", json_schema_extra={"examples": ["evnnmvHTCgIn"]}
    )
    title: Optional[StrictStr] = Field(
        default=None,
        description='Title at the time of the change (may be "[protected]" for protected notes)',
    )
    current_title: Optional[StrictStr] = Field(
        default=None,
        description='Current title of the note (may be "[protected]" for protected notes)',
    )
    current_is_deleted: Optional[StrictBool] = Field(
        default=None,
        description="Whether the note is currently deleted",
        alias="current_isDeleted",
    )
    current_delete_id: Optional[StrictStr] = Field(
        default=None,
        description="Delete ID if the note is deleted",
        alias="current_deleteId",
    )
    current_is_protected: Optional[StrictBool] = Field(
        default=None,
        description="Whether the note is protected",
        alias="current_isProtected",
    )
    utc_date: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="utcDate",
        json_schema_extra={"examples": ["2021-12-31 19:18:11.930Z"]},
    )
    var_date: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="date",
        json_schema_extra={"examples": ["2021-12-31 20:18:11.930+0100"]},
    )
    can_be_undeleted: Optional[StrictBool] = Field(
        default=None,
        description="Whether the note can be undeleted (only present for deleted notes)",
        alias="canBeUndeleted",
    )
    __properties: ClassVar[List[str]] = [
        "noteId",
        "title",
        "current_title",
        "current_isDeleted",
        "current_deleteId",
        "current_isProtected",
        "utcDate",
        "date",
        "canBeUndeleted",
    ]

    @field_validator("note_id")
    def note_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[a-zA-Z0-9_]{4,32}", value):
            raise ValueError(
                r"must validate the regular expression /[a-zA-Z0-9_]{4,32}/"
            )
        return value

    @field_validator("utc_date")
    def utc_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z", value
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z/"
            )
        return value

    @field_validator("var_date")
    def var_date_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\+\-][0-9]{4}",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\+\-][0-9]{4}/"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecentChange from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecentChange from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "noteId": obj.get("noteId"),
                "title": obj.get("title"),
                "current_title": obj.get("current_title"),
                "current_isDeleted": obj.get("current_isDeleted"),
                "current_deleteId": obj.get("current_deleteId"),
                "current_isProtected": obj.get("current_isProtected"),
                "utcDate": obj.get("utcDate"),
                "date": obj.get("date"),
                "canBeUndeleted": obj.get("canBeUndeleted"),
            }
        )
        return _obj
