# coding: utf-8

"""
    ETAPI

    External Trilium API

    The version of the OpenAPI document: 1.0.0
    Contact: contact@eliandoran.me
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class Revision(BaseModel):
    """
    Revision represents a snapshot of note's title and content at some point in the past.
    """  # noqa: E501

    revision_id: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="revisionId",
        json_schema_extra={"examples": ["evnnmvHTCgIn"]},
    )
    note_id: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None, alias="noteId", json_schema_extra={"examples": ["evnnmvHTCgIn"]}
    )
    type: Optional[StrictStr] = None
    mime: Optional[StrictStr] = None
    is_protected: Optional[StrictBool] = Field(default=None, alias="isProtected")
    title: Optional[StrictStr] = None
    blob_id: Optional[StrictStr] = Field(
        default=None,
        description="ID of the blob object which effectively serves as a content hash",
        alias="blobId",
    )
    date_last_edited: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="dateLastEdited",
        json_schema_extra={"examples": ["2021-12-31 20:18:11.930+0100"]},
    )
    date_created: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="dateCreated",
        json_schema_extra={"examples": ["2021-12-31 20:18:11.930+0100"]},
    )
    utc_date_last_edited: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="utcDateLastEdited",
        json_schema_extra={"examples": ["2021-12-31 19:18:11.930Z"]},
    )
    utc_date_created: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="utcDateCreated",
        json_schema_extra={"examples": ["2021-12-31 19:18:11.930Z"]},
    )
    utc_date_modified: Optional[Annotated[str, Field(strict=True)]] = Field(
        default=None,
        alias="utcDateModified",
        json_schema_extra={"examples": ["2021-12-31 19:18:11.930Z"]},
    )
    content_length: Optional[StrictInt] = Field(default=None, alias="contentLength")
    __properties: ClassVar[List[str]] = [
        "revisionId",
        "noteId",
        "type",
        "mime",
        "isProtected",
        "title",
        "blobId",
        "dateLastEdited",
        "dateCreated",
        "utcDateLastEdited",
        "utcDateCreated",
        "utcDateModified",
        "contentLength",
    ]

    @field_validator("revision_id")
    def revision_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[a-zA-Z0-9_]{4,32}", value):
            raise ValueError(
                r"must validate the regular expression /[a-zA-Z0-9_]{4,32}/"
            )
        return value

    @field_validator("note_id")
    def note_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"[a-zA-Z0-9_]{4,32}", value):
            raise ValueError(
                r"must validate the regular expression /[a-zA-Z0-9_]{4,32}/"
            )
        return value

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "text",
                "code",
                "render",
                "file",
                "image",
                "search",
                "relationMap",
                "book",
                "noteMap",
                "mermaid",
                "webView",
                "shortcut",
                "doc",
                "contentWidget",
                "launcher",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('text', 'code', 'render', 'file', 'image', 'search', 'relationMap', 'book', 'noteMap', 'mermaid', 'webView', 'shortcut', 'doc', 'contentWidget', 'launcher')"
            )
        return value

    @field_validator("date_last_edited")
    def date_last_edited_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\+\-][0-9]{4}",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\+\-][0-9]{4}/"
            )
        return value

    @field_validator("date_created")
    def date_created_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\+\-][0-9]{4}",
            value,
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}[\+\-][0-9]{4}/"
            )
        return value

    @field_validator("utc_date_last_edited")
    def utc_date_last_edited_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z", value
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z/"
            )
        return value

    @field_validator("utc_date_created")
    def utc_date_created_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z", value
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z/"
            )
        return value

    @field_validator("utc_date_modified")
    def utc_date_modified_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(
            r"[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z", value
        ):
            raise ValueError(
                r"must validate the regular expression /[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3}Z/"
            )
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Revision from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "is_protected",
                "content_length",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Revision from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "revisionId": obj.get("revisionId"),
                "noteId": obj.get("noteId"),
                "type": obj.get("type"),
                "mime": obj.get("mime"),
                "isProtected": obj.get("isProtected"),
                "title": obj.get("title"),
                "blobId": obj.get("blobId"),
                "dateLastEdited": obj.get("dateLastEdited"),
                "dateCreated": obj.get("dateCreated"),
                "utcDateLastEdited": obj.get("utcDateLastEdited"),
                "utcDateCreated": obj.get("utcDateCreated"),
                "utcDateModified": obj.get("utcDateModified"),
                "contentLength": obj.get("contentLength"),
            }
        )
        return _obj
